// A naive MPI parallel sparse matrix vector multiplication (MatMult)

#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

// Petsc MATMPIAIJ matrix
typedef struct {
  int     m, n; // local row/column size
  int     M, N; // global row/cloum size
  int    *i;    // row pointer
  int    *j;    // column indices
  double *a;    // values

  int  rstart, rend; // [start, end) of row indices on this process
  int *rrange;
  int  cstart, cend; // [start, end) of column indices on this process
  int *crange;
} Mat;

// Petsc VECMPI vector
typedef struct {
  int     n, N; // local/global size
  double *a;    // values
} Vec;

// For simplicity, use global variables to store an NR x NC matrix A with NNZ nonzeros in the CSR format, and two vectors X, Z with Z = AX.
// The example was generated by the Python script crs.py
#define NR  32
#define NC  36
#define NNZ 50
static int    Gi[NR + 1] = {0, 1, 2, 2, 4, 5, 7, 9, 9, 12, 16, 19, 21, 23, 25, 26, 27, 28, 30, 30, 32, 34, 37, 37, 39, 40, 40, 41, 43, 46, 47, 48, 50};
static int    Gj[NNZ]    = {1, 22, 8, 15, 5, 0, 16, 15, 34, 3, 9, 27, 8, 14, 20, 31, 12, 13, 23, 5, 20, 0, 20, 13, 28, 21, 0, 0, 23, 33, 9, 23, 13, 24, 15, 30, 33, 1, 29, 11, 30, 4, 23, 5, 21, 30, 17, 5, 16, 34};
static double Ga[NNZ]    = {3, 8, 7, 3, 2, 1, 7, 3, 4, 4, 4, 7, 4, 5, 6, 4, 2, 6, 5, 7, 2, 5, 8, 9, 6, 8, 4, 4, 3, 7, 3, 2, 8, 5, 8, 8, 4, 9, 4, 1, 1, 4, 5, 9, 6, 3, 4, 5, 1, 5};
static double Xa[NC]     = {5, 2, 6, 1, 3, 7, 1, 7, 6, 5, 9, 6, 5, 4, 2, 6, 5, 5, 7, 3, 4, 8, 6, 4, 4, 1, 9, 7, 4, 9, 3, 3, 8, 9, 6, 1};
static double Za[NR]     = {6, 48, 0, 60, 14, 40, 42, 0, 73, 70, 54, 57, 57, 60, 64, 20, 20, 75, 0, 23, 52, 108, 0, 54, 6, 0, 3, 32, 120, 20, 35, 35};

int main(int argc, char **argv)
{
  Mat    A; // MPI parallel representation of the matrix
  Vec    x, y, z;
  double norm = 0;
  int    rank, size;
  int    m; // Number of rows on the current MPI process
  int    n; // Number of columns on the current MPI process

  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &size);

  // Distribute A by rows
  m = NR / size + ((NR % size) > rank ? 1 : 0); // Actually in petsc one can set m arbitrarily, as long as SUM(m) = NR
  n = NC / size + ((NC % size) > rank ? 1 : 0); // Actually in petsc one can set n arbitrarily, as long as SUM(n) = NC

  // Compute A row ownership
  A.rrange    = (int *)malloc(sizeof(int) * (size + 1));
  A.rrange[0] = 0;
  MPI_Allgather(&m, 1, MPI_INT, A.rrange + 1, 1, MPI_INT, MPI_COMM_WORLD);
  for (int i = 0; i < size; i++) A.rrange[i + 1] += A.rrange[i];
  A.rstart = A.rrange[rank];
  A.rend   = A.rrange[rank + 1];

  // Compute A column partition. Columns are not distributed, but have an imaginary partition conforming to the distribution of x in y = Ax
  A.crange    = (int *)malloc(sizeof(int) * (size + 1));
  A.crange[0] = 0;
  MPI_Allgather(&n, 1, MPI_INT, A.crange + 1, 1, MPI_INT, MPI_COMM_WORLD);
  for (int i = 0; i < size; i++) A.crange[i + 1] += A.crange[i];
  A.cstart = A.crange[rank];
  A.cend   = A.crange[rank + 1];

  A.m = m;
  A.M = NR;
  A.n = n;
  A.N = NC;

  A.i    = (int *)malloc(sizeof(int) * (m + 1));
  A.i[0] = 0;
  for (int i = 0; i < m; i++) A.i[i + 1] = A.i[i] + (Gi[A.rstart + i + 1] - Gi[A.rstart + i]);

  A.j = Gj + Gi[A.rstart]; // Can directly reuse Gj, Ga, but not Gi
  A.a = Ga + Gi[A.rstart];

  // Distribute x according to A's column partition
  x.n = A.n;
  x.N = A.N;
  x.a = Xa + A.cstart;

  // Distribute y according to A's row distribution
  y.n = A.m;
  y.N = A.M;
  y.a = (double *)malloc(sizeof(double) * y.n);

  // Duplicate y to z, except the value array
  z.n = y.n;
  z.N = y.N;
  z.a = Za + A.rstart;

  // Use MPI_Allgatherv to gather the distributed x to a local X[]. We don't use Xa[] because we want to simulate real code where Xa[] is not available
  double *X          = (double *)malloc(sizeof(double) * x.N);
  int    *recvcounts = (int *)malloc(sizeof(int) * size);

  for (int i = 0; i < size; i++) recvcounts[i] = A.crange[i + 1] - A.crange[i];
  MPI_Allgatherv(x.a, x.n, MPI_DOUBLE, X, recvcounts, A.crange, MPI_DOUBLE, MPI_COMM_WORLD);

  // Compute y = Ax
  for (int i = 0; i < A.m; i++) {
    y.a[i] = 0.0;
    for (int j = A.i[i]; j < A.i[i + 1]; j++) y.a[i] += A.a[j] * X[A.j[j]];
  }

  // Compare y agaist the answer z by computing the norm of ||y - z||
  for (int i = 0; i < A.m; i++) norm += (y.a[i] - z.a[i]) * (y.a[i] - z.a[i]);

  MPI_Allreduce(MPI_IN_PLACE, &norm, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);

  free(A.rrange);
  free(A.crange);
  free(A.i);
  free(X);
  free(y.a);
  free(recvcounts);

  MPI_Finalize();
  if (rank == 0) {
    if (norm > 1e-6) {
      printf("Error in computing y = Ax, with norm = %f\n", norm);
      return 1;
    } else {
      printf("Succeeded in computing y = Ax\n");
      return 0;
    }
  }
}
